refactor: CICD 수정
## 작업 내용
EC2에 업로드 후 AMI 만들어서 Auto Scaling 그룹에 배포

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -76,9 +76,18 @@ jobs:
 
       - name: Create AMI
         run: |
-          INSTANCE_ID=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=ggumi" --query "Reservations[*].Instances[*].InstanceId" --output text)
-          echo "Instance ID: $INSTANCE_ID"
-          aws ec2 create-image --instance-id $INSTANCE_ID --name "ggumi-$(date +%Y%m%d%H%M%S)" --no-reboot
+#          INSTANCE_ID=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=ggumi" --query "Reservations[*].Instances[*].InstanceId" --output text)
+#          echo "Instance ID: $INSTANCE_ID"
+#          aws ec2 create-image --instance-id $INSTANCE_ID --name "ggumi-$(date +%Y%m%d%H%M%S)" --no-reboot
+#          INSTANCE_ID=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=ggumi" --query "Reservations[*].Instances[*].InstanceId" --output text)
+#
+          if [ -z "$INSTANCE_ID" ]; then
+            echo "Error: No instance found with the tag 'Name=ggumi'."
+            exit 1
+          else
+            echo "Instance ID: $INSTANCE_ID"
+            aws ec2 create-image —instance-id $INSTANCE_ID —name "ggumi-$(date +%Y%m%d%H%M%S)" —no-reboot
+          fi
 
       - name: Update Auto Scaling Group
         run: |
